version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - Ocramius
  assignees:
  - Ocramius
  labels:
  - dependencies
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: phar-io/version
    versions:
    - 3.1.0
  - dependency-name: symfony/polyfill-ctype
    versions:
    - 1.22.1
  - dependency-name: felixfbecker/language-server-protocol
    versions:
    - 1.5.1
  - dependency-name: symfony/polyfill-php73
    versions:
    - 1.22.1
  - dependency-name: symfony/string
    versions:
    - 5.2.2
  - dependency-name: symfony/console
    versions:
    - 5.2.2
